const channelsTypes = {
  CREATE_NEW_CHANNEL_START: "CREATE_NEW_CHANNEL_START",
  CREATE_NEW_CHANNEL_SUCCESS: "CREATE_NEW_CHANNEL_SUCCESS",
  CREATE_NEW_CHANNEL_FAILURE: "CREATE_NEW_CHANNEL_FAILURE",
  LOAD_ALL_CHANNELS_START: "LOAD_ALL_CHANNELS_START",
  LOAD_ALL_CHANNELS_SUCCESS: "LOAD_ALL_CHANNELS_SUCCESS",
  LOAD_ALL_CHANNELS_FAILURE: "LOAD_ALL_CHANNELS_FAILURE",
  SET_CURRENT_CHANNEL: "SET_CURRENT_CHANNEL",
};

export default channelsTypes;
