const userActionTypes = {
  CHECK_USER_SESSION_START: "CHECK_USER_SESSION_START",
  CHECK_USER_SESSION_SUCCESS: "CHECK_USER_SESSION_SUCCESS",
  CHECK_USER_SESSION_FAILURE: "CHECK_USER_SESSION_FAILURE",
};

export default userActionTypes;
